USE [master]
GO

/****** Object:  Database [TiendaMusical]    Script Date: 23/11/2020 00:34:33 ******/
CREATE DATABASE [TiendaMusical]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TiendaMusical}', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TiendaMusical}.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TiendaMusical}_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TiendaMusical}_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TiendaMusical].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TiendaMusical] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TiendaMusical] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TiendaMusical] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TiendaMusical] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TiendaMusical] SET ARITHABORT OFF 
GO

ALTER DATABASE [TiendaMusical] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TiendaMusical] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TiendaMusical] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TiendaMusical] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TiendaMusical] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TiendaMusical] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TiendaMusical] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TiendaMusical] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TiendaMusical] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TiendaMusical] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TiendaMusical] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TiendaMusical] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TiendaMusical] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TiendaMusical] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TiendaMusical] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TiendaMusical] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TiendaMusical] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TiendaMusical] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TiendaMusical] SET  MULTI_USER 
GO

ALTER DATABASE [TiendaMusical] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TiendaMusical] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TiendaMusical] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TiendaMusical] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TiendaMusical] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TiendaMusical] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TiendaMusical] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TiendaMusical] SET  READ_WRITE 
GO

